# ===================================
#  Relation Behavior Config
# ===================================

pageblocks:
    label: Page Block
    manage:
        list: ~/plugins/dietervyncke/pages/models/pageblock/columns.yaml
        form: ~/plugins/dietervyncke/pages/models/pageblock/fields.yaml
    view:
        list: ~/plugins/dietervyncke/pages/models/pageblock/columns.yaml
        defaultSort:
            column: sort_order
            direction: asc
    toolbar:
        buttons: block_reorder_toolbar

pagephotos:
    label: Page Photo
    manage:
        list: ~/plugins/dietervyncke/pages/models/pagephoto/columns.yaml
        form: ~/plugins/dietervyncke/pages/models/pagephoto/fields.yaml
    view:
        list: ~/plugins/dietervyncke/pages/models/pagephoto/columns.yaml
        defaultSort:
            column: sort_order
            direction: asc
    toolbar:
        buttons: photo_reorder_toolbar
