# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Page

# Model Form Field configuration
form: $/dietervyncke/pages/models/page/fields.yaml

# Model Class name
modelClass: dietervyncke\Pages\Models\Page

# Default redirect location
defaultRedirect: dietervyncke/pages/pages

# Create page
create:
    title: Create Page
    redirect: dietervyncke/pages/pages/update/:id
    redirectClose: dietervyncke/pages/pages

# Update page
update:
    title: Edit Page
    redirect: dietervyncke/pages/pages/
    redirectClose: dietervyncke/pages/pages
    form: $/dietervyncke/pages/models/page/fields_update.yaml

# Preview page
preview:
    title: Preview Page
