# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Page

# Model Form Field configuration
form: $/dieter/pages/models/page/fields.yaml

# Model Class name
modelClass: Dieter\Pages\Models\Page

# Default redirect location
defaultRedirect: dieter/pages/pages

# Create page
create:
    title: Create Page
    redirect: dieter/pages/pages/update/:id
    redirectClose: dieter/pages/pages

# Update page
update:
    title: Edit Page
    redirect: dieter/pages/pages/
    redirectClose: dieter/pages/pages
    form: $/dieter/pages/models/page/fields_update.yaml

# Preview page
preview:
    title: Preview Page
